#!/bin/bash

while read kasutajad1
do
	kasutaja=$kasutajad1
	parool=$(pwgen 7)
	useradd -m -s /bin/bash $kasutaja
	echo "$kasutaja parool on $parool"
	echo "$kasutaja:$parool" >> "Genereeritud_kasutajad"
done < $1
